# ---------------------------------------------------------------------------- #
# service: test centos6-httpd-php56
#
# $ docker build -t test-centos6-httpd-php56 .
# $ docker-compose up -d
# ---------------------------------------------------------------------------- #
version: '2'
services:
  web:
    container_name: test-centos6-httpd-php56
    image: test-centos6-httpd-php56
    volumes:
      - "./www:/var/www"
    environment:
      VIRTUAL_HOST: test-centos6-httpd-php56.docker
      VIRTUAL_NETWORK: nginx-proxy
    networks:
      - frontend
      - backend
networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
    driver: bridge
