# ---------------------------------------------------------------------------- #
# service: automated reverse proxy (*.docker)
# ---------------------------------------------------------------------------- #
version: '2'
services:
  proxy:
    container_name: proxy
    image: rckrdstrgrd/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d/__default.conf:/etc/nginx/conf.d/__default.conf:ro"
      - "./vhost.d:/etc/nginx/vhost.d:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./html:/var/www/html"
    networks:
      - frontend
      - backend
networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
    driver: bridge
